# Generated by Django 3.2.5 on 2022-02-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_do_point',
            name='pub_date',
        ),
    ]
